<?php

namespace app\home\controller\game;

use app\BaseController;
use app\common\traites\PublicCrudTrait;

use hg\apidoc\annotation as Apidoc;

/**
 *
 * @Apidoc\Title("麻将数据")
 * */
class MaJiang extends BaseController
{
    use PublicCrudTrait;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


    public function info(){
        echo 'info';
    }





// 类结束了     
}
