<?php


namespace app\home;


use app\BaseController;
use app\common\model\User;

class ApiBaseController extends BaseController
{
    public function initialize()
    {
        // 随便给一个数据 作为临时登录数据
        $user_info = (new User())->find(1);
        session('home_user',$user_info);
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}