<?php


namespace app\admin\controller\log;


use app\admin\controller\Base;
use app\common\model\LoginLog as models;
use think\facade\Db;

class LoginLog extends Base
{
    protected $model;

    /**
     * 登陆日志控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        //没办法区分type
        $list =$this->model->order('id desc')
            ->paginate(['list_rows'=>$limit,'page'=>$page])
            ->each(function($item, $key){
                $item->address = '';
                if (!empty($item->login_ip)){
                    $int = ip2long($item->login_ip);
                    //查询范围区间
                    $find = Db::name('common_data_ip')
                        ->cache(60)
                        ->where('num_start','<',$int)
                        ->where('num_end','>',$int)
                        ->find();
                    if ($find){
                        $item->address = $find['country'].$find['region'].$find['city'].$find['area'];
                    }
                }
                return $item;
            });;

         $this->success($list);
    }
}