<?php


namespace app\controller\log;


use app\controller\Base;
use app\model\MoneyLog as models;

class PayCash extends Base
{
    protected $model;

    /**
     * 提现控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {

        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = array_filter($this->request->post());

        $map = $date = [];
        //查询的状态
        $map[] = ['status', 'in', models::$withdrawal_status];

        isset($post['uid']) && $map[] = ['uid', '=', $post['uid']];
        isset($post['start']) && $date['start'] = $post['start'];
        isset($post['end']) && $date['end'] = $post['end'];
        $order = 'id desc';
        isset($post['create_time_sort']) && $order = 'id ' . $post['create_time_sort'];

        if (isset($post['user_name'])) {//查询指定用户的
            $map[] = $this->map_user_name($post['user_name']);
        } else {//查询所有//代理查询所有下级，管理员查询平台所有的用户
            $map[] = ['uid', 'in', $this->request->admin_user['user_all_list']];
        }

        $money = $this->model->count_money($map, [], $date);
        $list = $this->model->page_list($map, $limit, $page, $order, $date);
        $list = $list->toArray();
        $list['money'] = $money;
        $list['status_name'] = '提现：';
        $this->success($list);
    }

    //洗码列表
    public function xima_list()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = array_filter($this->request->post());
        $date = [];
        isset($post['start']) && $date['start'] = $post['start'];
        isset($post['end']) && $date['end'] = $post['end'];
        $map[] = ['status', 'in', \app\model\MoneyLog::$xima_status];

        if (isset($post['user_name'])) {//查询指定用户的
            $map[] = $this->map_user_name($post['user_name'], 'direct_list', 'uid');
        } else {
            $map[] = ['uid', 'in', array_merge_func($this->request->admin_user['user_list'], $this->request->admin_user['agent_list'])];
        }

        $list = $this->model->page_list($map, $limit, $page, 'id desc', $date);

        if (!$list) {
            $this->success('没有信息');
        }

        //激统计洗马金额
        $money = $this->model->count_money($map, [], $date);
        $list = $list->toArray();
        $list['money'] = $money;
        $this->success($list);
    }

    //代理授权列表
    public function auth_list()
    {

        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = array_filter($this->request->post());
        $date = [];
        isset($post['start']) && $date['start'] = $post['start'];
        isset($post['end']) && $date['end'] = $post['end'];
        $map = [];
        if (isset($post['user_name'])) {//查询指定用户的
            $map[] = $this->map_user_name($post['user_name']);
        } else {//查询所有//代理查询所有下级，管理员查询平台所有的用户
            $map[] = ['uid', 'in', array_merge_func($this->request->admin_user['agent_list'],$this->request->admin_user['user_list'])];
        }

        $map[] = ['status', 'in', array_merge_func(models::$recharge_status, models::$withdrawal_status)];
        $money = $this->model->count_money($map, [], $date);
        $list = $this->model->page_list($map, $limit, $page, 'id desc', $date);

        if (!$list) {
            $this->success('没有信息');
        }

        $list = $list->toArray();
        $list['money'] = $money;
        $this->success($list);
    }

    //下注资金列表
    public function record_list()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = array_filter($this->request->post());
        $date = [];
        isset($post['start']) && $date['start'] = $post['start'];
        isset($post['end']) && $date['end'] = $post['end'];
        $money = 0;
        $name = '';

        if (isset($post['user_name'])) {//查询指定用户的
            $map[] = $this->map_user_name($post['user_name']);
        } else {
           $map[] = ['uid', 'in',  $this->request->admin_user['user_all_list']];
        }

        $map[] = ['status', 'in', models::$game_order_status];
        $money = $this->model->count_money($map, [], $date);
        $list = $this->model->page_list($map, $limit, $page, 'id desc', $date);

        $list = $list->toArray();
        $list['money'] = $money;
        $this->success($list);
    }
}