<?php


namespace app\controller\log;


use app\controller\Base;
use app\model\MoneyLog as models;

class PayRecharge extends Base
{
    protected $model;

    /**
     * 充值控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {

        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = array_filter($this->request->post());
        $map = $date = [];
        $order = 'id desc';
        isset($post['create_time_sort']) && $order = 'id ' . $post['create_time_sort'];
        //代理查询存在是，清除其他查询只保留代理查询
        isset($post['start']) && $date['start'] = $post['start'];
        isset($post['end']) && $date['end'] = $post['end'];

        //查询的状态
        $map[] = ['status','in',models::$recharge_status];

        isset($post['uid']) && $map[] = ['uid', '=', $post['uid']];

        if (isset($post['user_name'])) {//查询指定用户的
            $map[] = $this->map_user_name($post['user_name']);
        } else {//查询所有//代理查询所有下级，管理员查询平台所有的用户
                $map[] = ['uid', 'in', $this->request->admin_user['user_list']];
        }

        $money = $this->model->count_money($map, [],$date);
        $list = $this->model->page_list($map, $limit, $page, $order, $date);
        $list = $list->toArray();
        $list['money'] = $money;
        $list['status_name'] = '充值：';
        $this->success($list);
    }
}